import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("weather.csv")
print("First 10 rows of weather data:")
print(df.head(10))
max_temperature = df["temperature"].max()
min_temperature = df["temperature"].min()
print("\nMaximum temperature:", max_temperature)
print("Minimum temperature:", min_temperature)
places_less_than_28 = df[df["temperature"] < 28][["place", "temperature"]]
print("\nPlaces with temperature less than 28°C:")
print(places_less_than_28)
cloudy_places = df[df["weather"] == "Cloudy"][["place", "weather"]]
print("\nPlaces with weather = 'Cloudy':")
print(cloudy_places)
weather_frequency = df["weather"].value_counts().sort_index()
print("\nWeather frequency:")
print(weather_frequency)
plt.figure(figsize=(10,6))
plt.bar(df["date"], df["temperature"])
plt.xlabel("Date")
plt.ylabel("Temperature")
plt.title("Temperature of each day")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()
